# Generated by Django 3.1.7 on 2021-04-08 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_auto_20210407_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediario',
            name='Placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.carros', unique=True),
        ),
    ]
